
- name: Apply User Configuration
  hosts: target
  become: yes

  vars_files:
    - users.yml
    - user_roles.yml

  tasks:

    - name: Ensure groups exist
      group:
        name: "{{ item }}"
        state: present
      loop: >-
          {{
            users | map(attribute='role')
                  | map('extract',roles)
                  | map(attribute='groups')
                  | flatten
                  | unique
           }}    
        

    - name: Manage users
      user:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        shell: "{{ item.shell | default('/bin/bash') }}"
        groups: "{{ roles[item.role].groups | join(',') }}"
        append: yes
      loop: "{{ users }}"

    - name: Add SSH keys
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', item.ssh_key) }}"
      when: item.state == 'present'
      loop: "{{ users }}"


      - name: Configure sudo access
       copy:
         dest: "/etc/sudoers.d/{{ item.name }}"
         content: "{{ item.name }} {{ roles[item.role].sudo }}"
         mode: '0440'
         validate: '/usr/sbin/visudo -cf %s'
       when: roles[item.role].sudo != ""
       loop: "{{ users }}"
