- name: Apply User configuration
  hosts: target
  become: yes

  vars_files:
    - ../vars/users.yml
    - ../vars/user_roles.yml

  tasks:

    - name: Ensure existence of groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: >-
        {{
          users
          | map(attribute='role')
          | map('extract', roles)
          | map(attribute='groups')
          | flatten
          | unique
        }}

    - name: Create Users
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ roles[item.role].groups | join(',') }}"
        append: yes
        password_lock: true
        shell: "{{ item.shell }}"
        state: "{{ item.state }}"
      loop: "{{ users }}"

    - name: Ensure SSH Directories exist
      ansible.builtin.file:
        path: "/home/{{ item.username }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
      when: item.state == "present"
      loop: "{{ users }}"

    - name: Create SSH Key pair for users (control node)
      delegate_to: localhost
      ansible.builtin.openssh_keypair:
        path: "../files/{{ item.username }}"
        type: ed25519
        mode: '0600'
      when: item.state == "present"
      loop: "{{ users }}"

    - name: Add SSH key to authorized Key
      ansible.posix.authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', '../files/' + item.username + '.pub') }}"
        state: present
      when: item.state == "present"
      loop: "{{ users }}"

    - name: Setup sudo access
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ item.username }}"
        content: "{{ item.username }} {{ roles[item.role].sudo | trim }}"
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
      when:
        - item.state == "present"
        - roles[item.role].sudo | length > 0
      loop: "{{ users }}"
