name: Ansible User CI/CD

on:
  push: 
    paths: 
      - 'playbooks/**'
      - 'vars/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
             

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
      - name: Install Ansible collection
        run: |
          ansible-galaxy collection install community.crypto ansible.posix

      - name: Setup ssh key 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run playbook
        run: |
          ansible-playbook -i inventory playbooks/user_management.yml      
