name: Ansible User CI/CD

on:
  push: 
    paths: 
      - 'playbooks/**'
      - 'vars/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Show generated keys
        run: |
           pwd
           ls -l
           ls -l files
          

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup ssh key 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run playbook
        run: |
          ansible-playbook -i inventory playbooks/user_management.yml

      - name: Validate user
        run: |
          ansible target -i inventory -m command -a "id sudip"
      - name: Validate Groups
        run: |
          ansible target -i inventory -m command -a "groups sudip"

      - name: CHeck SSH Directory
        run: |
           ansible target -i inventory -m shell -a "sudo ls -ld /home/sudip/.ssh"

      - name: Check Sudo
        run: |
          ansible target -i inventory -m shell -a "sudo -l -U sudip"
          

      
